.TH "ConsoleController" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConsoleController \- The ConsoleContextualizationController class is responsible for controll the Contextualization Tool application when is executed from a terminal (CLI)\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <consolecontroller\&.h>\fP
.PP
Inherits \fBContextualizationController\fP\&.
.PP
Inherited by \fBLinuxConsoleController\fP, and \fBWindowsConsoleController\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBActionType\fP { \fBPrintHelp\fP = 0, \fBNoAction\fP, \fBListProjects\fP, \fBDetailProject\fP, \fBNewProject\fP, \fBDeleteProject\fP, \fBSelectProject\fP, \fBClearStrings\fP, \fBClearImage\fP, \fBClearAll\fP, \fBAddString\fP, \fBRemoveString\fP, \fBSelectString\fP, \fBUnselectString\fP, \fBSetImage\fP, \fBCaptureArea\fP, \fBDetectStrings\fP, \fBExportProject\fP, \fBImportProject\fP, \fBSend\fP, \fBProcessFiles\fP, \fBPrintClearHelp\fP, \fBPrintAddHelp\fP, \fBPrintDetectHelp\fP, \fBPrintImageHelp\fP }"
.br
.RI "Constains all actions that can be done by the exec function\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsoleController\fP ()"
.br
.RI "Creates an empty controller\&. "
.ti -1c
.RI "\fBConsoleController\fP (int argc, char **argv)"
.br
.RI "Creates a controller decoding arguments received by argument\&. "
.ti -1c
.RI "void \fBexec\fP ()"
.br
.RI "Executes the logic of controller\&. "
.ti -1c
.RI "bool \fBdecodeArguments\fP (int argc, char **argv)"
.br
.RI "Decode arguments entered to set the behavior of the exec method\&. "
.ti -1c
.RI "void \fBsetAction\fP (\fBActionType\fP action, QVariant parameter=QVariant())"
.br
.RI "Sets the action to be executed and his parameter,\&. "
.ti -1c
.RI "void \fBprintUsage\fP ()"
.br
.RI "Print in screen the general usage of application\&. "
.ti -1c
.RI "void \fBprintClearDetails\fP ()"
.br
.RI "Print extended help for clear command\&. "
.ti -1c
.RI "void \fBprintAddDetails\fP ()"
.br
.RI "Print extended help for add command\&. "
.ti -1c
.RI "void \fBprintDetectDetails\fP ()"
.br
.RI "Print extended help for detect command\&. "
.ti -1c
.RI "void \fBprintImageDetails\fP ()"
.br
.RI "Print extended help for image command\&. "
.ti -1c
.RI "void \fBprintDetectOptions\fP ()"
.br
.RI "Print extended help for detect command\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
The ConsoleContextualizationController class is responsible for controll the Contextualization Tool application when is executed from a terminal (CLI)\&. 

This is the controller class that works a CLI environment\&. 
.PP
Definition at line 26 of file consolecontroller\&.h\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBConsoleController::ActionType\fP"

.PP
Constains all actions that can be done by the exec function\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPrintHelp \fP\fP
Indicates that the app have to print the general help\&. 
.TP
\fB\fINoAction \fP\fP
Indicates that the app have to do anything\&. 
.TP
\fB\fIListProjects \fP\fP
Indicates that the app have to list all available projects\&. 
.TP
\fB\fIDetailProject \fP\fP
Indicates that the app have to show detail for avitve project\&. 
.TP
\fB\fINewProject \fP\fP
Indicates that the app have to create new project\&. 
.TP
\fB\fIDeleteProject \fP\fP
Indicates that the app have to delete a project\&. 
.TP
\fB\fISelectProject \fP\fP
Indicates that the app have to ativate a project\&. 
.TP
\fB\fIClearStrings \fP\fP
Indicates that the app have to clear all strings from the active project\&. 
.TP
\fB\fIClearImage \fP\fP
Indicates that the app have to unset current image from the active project\&. 
.TP
\fB\fIClearAll \fP\fP
Indicates that the app have to empty the active project\&. 
.TP
\fB\fIAddString \fP\fP
Indicates that the app have to add new string in the active project\&. 
.TP
\fB\fIRemoveString \fP\fP
Indicates that the app have to remove a string from the active project\&. 
.TP
\fB\fISelectString \fP\fP
Indicates that the app have to select the string indicated by user\&. 
.TP
\fB\fIUnselectString \fP\fP
Indicates that the app have to unselect the string indicated by user\&. 
.TP
\fB\fISetImage \fP\fP
Indicates that the app have to set the image in the active project\&. 
.TP
\fB\fICaptureArea \fP\fP
Indicates that the app have to let the user capture an area of sreen and set it as image model\&. 
.TP
\fB\fIDetectStrings \fP\fP
Indicates that the app have to extract strings from image model and add it in active project\&. 
.TP
\fB\fIExportProject \fP\fP
Indicates that the app have to save the active project in the path entered by the user\&. 
.TP
\fB\fIImportProject \fP\fP
Indicates that the app have to import a project entered by the user\&. 
.TP
\fB\fISend \fP\fP
Indicates that the app have to send the active contextualization\&. 
.TP
\fB\fIProcessFiles \fP\fP
Indicates that the app have to process files and storage VALIDADED strings\&. 
.TP
\fB\fIPrintClearHelp \fP\fP
Indicates that the app have to print detailed help for clear command\&. 
.TP
\fB\fIPrintAddHelp \fP\fP
Indicates that the app have to print extended help for add command\&. 
.TP
\fB\fIPrintDetectHelp \fP\fP
Indicates that the app have to print extended help for detect command\&. 
.TP
\fB\fIPrintImageHelp \fP\fP
Indicates that the app have to print extended help for image command\&. 
.PP
Definition at line 33 of file consolecontroller\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConsoleController::ConsoleController (int argc, char ** argv)"

.PP
Creates a controller decoding arguments received by argument\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP Number of argv elements\&. 
.br
\fIargv\fP Arguments entered by the user when executed the app\&. 
.RE
.PP

.PP
Definition at line 22 of file consolecontroller\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "bool ConsoleController::decodeArguments (int argc, char ** argv)"

.PP
Decode arguments entered to set the behavior of the exec method\&. The first element of argv always must be the name of the app\&. 
.PP
\fBParameters:\fP
.RS 4
\fIargc\fP Number of argv elements\&. 
.br
\fIargv\fP Arguments to decode\&. 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.PP
Definition at line 120 of file consolecontroller\&.cpp\&.
.SS "void ConsoleController::exec ()"

.PP
Executes the logic of controller\&. It has mutiples type of behavior depending the value of action_ variable\&.
.PP
Types of action can be shown in ActionType enum\&. 
.PP
Definition at line 36 of file consolecontroller\&.cpp\&.
.SS "void ConsoleController::setAction (\fBActionType\fP action, QVariant parameter = \fCQVariant()\fP)\fC [inline]\fP"

.PP
Sets the action to be executed and his parameter,\&. 
.PP
\fBParameters:\fP
.RS 4
\fIaction\fP Actions to be executed by \fBexec()\fP function\&. 
.br
\fIparameter\fP Required parameter to execute the action\&. 
.RE
.PP

.PP
Definition at line 244 of file consolecontroller\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
