.TH "src/contextualization/controller/consolecontroller.h" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/contextualization/controller/consolecontroller.h
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <QVariant>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <iomanip>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include 'contextualization/controller/contextualizationcontroller\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBConsoleController\fP"
.br
.RI "The ConsoleContextualizationController class is responsible for controll the Contextualization Tool application when is executed from a terminal (CLI)\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBconsolecontroller\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
