.TH "src/contextualization/model/contextualizationmodel.h" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/contextualization/model/contextualizationmodel.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QString>\fP
.br
\fC#include <QList>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include 'firmwarestring\&.h'\fP
.br
\fC#include 'src/tools/log\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContextualizationModel\fP"
.br
.RI "This is the model class of a MVC architecture on Contextualization Tool app\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBcontextualizationmodel\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
