.TH "src/storage/fpfileconnector.h" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/storage/fpfileconnector.h
.SH SYNOPSIS
.br
.PP
\fC#include <QFile>\fP
.br
\fC#include <QFileInfo>\fP
.br
\fC#include <QDir>\fP
.br
\fC#include 'databaseconnectorabstract\&.h'\fP
.br
\fC#include 'contextualization/model/firmwarestring\&.h'\fP
.br
\fC#include 'tools/utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFpFileConnector\fP"
.br
.RI "This is a class to access a database saved as fp file by HP company\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBfpfileconnector\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
