.TH "src/tools/hpcontextualizationfactory.h" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tools/hpcontextualizationfactory.h
.SH SYNOPSIS
.br
.PP
\fC#include 'contextualizationfactoryabstract\&.h'\fP
.br
\fC#include 'contextualization/controller/linuxconsolecontroller\&.h'\fP
.br
\fC#include 'contextualization/controller/linuxguicontroller\&.h'\fP
.br
\fC#include 'contextualization/controller/windowsconsolecontroller\&.h'\fP
.br
\fC#include 'contextualization/controller/windowsguicontroller\&.h'\fP
.br
\fC#include 'tools/utils\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHpContextualizationFactory\fP"
.br
.RI "This is a factory to create a concrete class of \fBContextualizationController\fP specific for HP company\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBhpcontextualizationfactory\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
