.TH "src/contextualization/controller/linuxguicontroller.cpp" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/contextualization/controller/linuxguicontroller.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'linuxguicontroller\&.h'\fP
.br

.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBlinuxguicontroller\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
