.TH "src/main.cpp" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.cpp \- This main file to exec program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QApplication>\fP
.br
\fC#include <QQmlApplicationEngine>\fP
.br
\fC#include <QQmlContext>\fP
.br
\fC#include 'tools/hpcontextualizationfactory\&.h'\fP
.br
\fC#include <QDebug>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
This main file to exec program\&. 


.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBmain\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"
The GuiContextualizationController class is registered as a type, which is accessible from QML by importing the URL, 'io\&.controllers\&.guicontroller 1\&.0'\&.
.PP
Definition at line 16 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
