.TH "src/storage/mysqlconnector.h" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/storage/mysqlconnector.h
.SH SYNOPSIS
.br
.PP
\fC#include <QtSql/QSqlDatabase>\fP
.br
\fC#include <QtSql/QSqlQuery>\fP
.br
\fC#include <QtSql/QSqlError>\fP
.br
\fC#include 'contextualization/model/firmwarestring\&.h'\fP
.br
\fC#include 'databaseconnectorabstract\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMySqlConnector\fP"
.br
.RI "This is a class to access a MySQL database\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBmysqlconnector\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
