.TH "src/contextualization/model/string.h" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/contextualization/model/string.h
.SH SYNOPSIS
.br
.PP
\fC#include <QString>\fP
.br
\fC#include <QJsonDocument>\fP
.br
\fC#include <QJsonObject>\fP
.br
\fC#include <QRegularExpression>\fP
.br
\fC#include 'tools/log\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBString\fP"
.br
.RI "This is the representation of a string with their properties\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBstring\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
