.TH "src/contextualization/controller/windowsguicontroller.h" 3 "Thu Sep 6 2018" "Version 1.0" "Contextualization Tool" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/contextualization/controller/windowsguicontroller.h
.SH SYNOPSIS
.br
.PP
\fC#include 'guicontroller\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowsGuiController\fP"
.br
.RI "This is the controller class that works a GUI Windows environment\&. "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
Jorge Herrero Tardón (jorgeht@usal.es) 
.RE
.PP
\fBDate:\fP
.RS 4
20/02/2018 
.RE
.PP
\fBVersion:\fP
.RS 4
1\&.0 
.RE
.PP

.PP
Definition in file \fBwindowsguicontroller\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Contextualization Tool from the source code\&.
